version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: docker_project
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/docker_project
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && npm start"

  cypress:
    image: cypress/included:latest
    environment:
      - CYPRESS_baseUrl=http://app:3000
    depends_on:
      - app
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.config.js:/app/cypress.config.js
    working_dir: /app
    entrypoint: cypress run 